### ISSUE TITLE
First release: 0.1.0

### ISSUE THREAD

**Issue by yuki24** [yuki24/artemis#1]
## 0.1.0

 * [x] #2: Add more test coverage
 * [x] #3: Add an `graphql:install` generator: `rails g graphql:install metaphysics https://metaphysics-production.artsy.net/`
 * [x] #4: Add support for GraphQL Fragments
 * [x] #5: Add an initializer that pre-configures the client with the info in `config/graphql.yml`
 * [x] #6: GraphQL files should be pre-loaded on boot in production
 * [x] #7: Add a `NetHttpPersistentAdapter`
 * [x] #8: Load the GraphQL log subscriber automatically
 * [x] #10: Raise a more helpful exception or retry after force-loading when the top-level constant is looked up
 * [x] #11: Add `before_execute` and `after_execute` callbacks
 * [x] #23: Load the graphql schema from `vendor/graphql/schema/service_name.json`
 * [x] #26: Add a rake task `rake graphql:schema:update`
 * [x] #31: Installer should not save a schema when it didn't receive a successful response
 * [x] #32: Raise an exception when the client receives 5xx
 * [x] #35: Add `Authorization` option to the installer

**Comment by yuki24** [comment]
Done: https://github.com/yuki24/artemis/releases/tag/v0.1.0

**Comment by jonallured** [comment]
Nice job!! 🎉
