### ISSUE TITLE
Second release: 0.2.0

### ISSUE THREAD

**Issue by yuki24** [yuki24/artemis#33]
## Features

 * [x] #28: Add a query generator: `rails g artemis:query QueryType [filename]`
 * [x] #29: Add a mutation generator: `rails g artemis:mutation MutationType [filename]`
 * [x] #30: Installer should add a new service when config/graphql.yml is already present

**Comment by yuki24** [comment]
closed by 0c4f88c5359547ef4b90b90bd3271dbcd9a265e2
