### ISSUE TITLE
Third release: 0.3.0

### ISSUE THREAD

**Issue by yuki24** [yuki24/artemis#44]
## Features

 * [ ] #20: Add support for GlobalID
 * [ ] #21: Expose the TestAdapter as a public API

## Internal changes

 * [ ] #9: Re-write the tests for Railtie in Rspec or the rest of the tests in Minitest
 * [ ] #24: Use GitHub's GraphQL API in the examples and tests

**Comment by yuki24** [comment]
closing in favor of https://github.com/yuki24/artemis/projects/1
